const express = require("express");
const router = express.Router();
const multiparty = require("connect-multiparty");
const multipartyMiddleware = multiparty();
const nodemailer = require("nodemailer");
const AWS = require("aws-sdk");
const s3 = new AWS.S3();
const fs = require("fs");

const myBucket = "igor-lein-bucket";

/* GET home page. */
router.get("/", function(req, res, next) {
  res.render("index", { title: "Express" });
});

/* GET test request. */
router.get("/test", function(req, res, next) {
  console.log("send email");

  const transport = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "81e82a0d81eb42", //generated by Mailtrap
      pass: "b3f3c64b9a8297" //generated by Mailtrap
    }
  });
  const mailOptions = {
    from: "igor.lein89@gmail.com",
    to: "igor.lein@plannuh.com",
    subject: "Nice Nodemailer test",
    text: "Hey there, it’s our first message sent with Nodemailer ;) ",
    html:
      "<b>Hey there! </b><br> This is our first message sent with Nodemailer"
  };

  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }
    console.log("Message sent: %s", info.messageId);
  });

  res.send({ data: "test" });
});

/* POST upload file request. */
router.post("/upload", multipartyMiddleware, function(req, res, next) {
  const { file } = req.files;
  fs.readFile(file.path, function(err, data) {
    const params = {
      Bucket: myBucket,
      Key: file.name,
      Body: data,
      ACL: "public-read"
    };
    s3.upload(params, function(err, data) {
      if (err) {
        console.log(err);
      } else {
        console.log("Successfully uploaded data to myBucket/myKey");
        res.send({ data });
      }
    });
  });
});

module.exports = router;
